services:
  db:
    image: "postgres:13"
    container_name: 'order'
    environment:
      POSTGRES_DB: orders_manager
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'user'
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:


