apiVersion: v1
kind: Service
metadata:
  name: orders-manager-service
spec:
  type: NodePort
  selector:
    app: orders-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432